### ISSUE TITLE
iOS Sample Gallery link in ReadMe goes to wrong page

### ISSUE THREAD

**Issue by FinHorsley** [xamarin/ios-samples#366]
The link in the ReadMe does go to the iOS Samples section of the developer.xamarin.com site, but the projects at the top of the page (which you see first), are not iOS based samples

For reference the link is in this section of the ReadMe

iOS/tvOS/watchOS Samples
========================

The samples in this directory use the Xamarin.iOS toolchain and
Xamarin Studio project files to illustrate the basics of how to
work with iOS and the SDK. Visit the [iOS Sample Gallery](https://developer.xamarin.com/samples/ios/all/)
to download individual samples.

**Comment by rolfbjarne** [comment]
If I click on the "iOS Sample Gallery" link, it takes me here: https://developer.xamarin.com/samples/ios/all/, which lists all the samples that can run on iOS (which are not only samples from this repository, we have multiple repositories with samples, such as xamarin/mac-ios-samples, xamarin/mobile-samples, etc.)

As far as I can tell this looks like the expected behavior, but maybe I'm missing something?

**Comment by conceptdev** [comment]
As Rolf said, it seems to go to this link which is the correct place
https://developer.xamarin.com/samples/ios/all/

I do see a couple of Xamarin.Forms samples - Accessibility, Native Views, and more - but there are also many iOS-specific samples in the list.

We are currently working on a new samples portal which will hopefully address filtering/searching issues with the current page.
