### ISSUE TITLE
Vision Faces sample can't stop at breakpoint

### ISSUE THREAD

**Issue by misakikaoru2006** [xamarin/ios-samples#405]
![2020_0828_1146_08](https://user-images.githubusercontent.com/11881920/91515760-d4698100-e924-11ea-825c-720e21b94b3a.jpg)

I used your example of Vision Faces to build my iOS app with Vision Fices in Xamarin C#. It is very cool and useful, but I found some strange move.
I'm afraid this is an elementary question.

#### The Method does not fire.
I started debugging with the actual iPad.
Windows10+Visual Studio 2019 Community+MacBookPro+iPad combination.
Debugging launched.

The ViewDidLoad() method worked and the application worked.
I confirmed this by placing a breakpoint in the ViewDidLoad() method.
When it detects a face, it puts a yellow frame on the face part of the photo on the iPad screen.

However, even if I place a breakpoint in the HandleRectangles method, debugging doesn't stop at the breakpoint.
How can I get it to stop at the breakpoint?

**Comment by whitneyschmidt** [comment]
@misakikaoru2006 Thank you for your feedback - there are no elementary questions and we are all learning!

I'm not exactly sure what is going on here, but I do notice one thing. In the screenshot you attached it looks like you've modified ViewController.cs without saving it - the * next to the filename at the top of the IDE indicates that a file hasn't been saved. If you make changes to a file and try and debug breakpoints without saving, the compiled + running version of the code doesn't line up with the breakpoints in the modified version.

After saving the ViewController.cs and cleaning + rebuilding, are you able to hit the breakpoints as expected?

If not, it would be useful for us to have full build logs and version information in order to investigate:

- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:

- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

Then copy/paste the version information (you can use the "Copy Information" button).

We look forward to hearing from you!

**Comment by rolfbjarne** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
