### ISSUE TITLE
SimpleCollectionView can not reuse cells

### ISSUE THREAD

**Issue by trunghaiy** [xamarin/ios-samples#59]
According to [this guide](http://developer.xamarin.com/guides/ios/user_interface/introduction_to_collection_views/) from Xamarin's guide, I think the sample with SimpleCollectionView should reuses cell but it doesn't.

I ran the demo with flowLayout, it always call to AnimalCell' constructor to init new Cell instead of reuse from reusable cell.

**Comment by olegoid** [comment]
@KMullins-Xam could you please check this issue, since this is something related to guides and documentation.

**Comment by rzaitov** [comment]
I run this sample and it has a simple circle layout with 21 cell on a screen.
There is no way to reuse the cells because all cell are on the screen (all 21 instance of the cell have to be created in order to be displayed on the screen).

![img_0255](https://cloud.githubusercontent.com/assets/2273285/23070301/b91530ba-f53b-11e6-8ac9-07542e88dea7.PNG)

Cell reusing is comming into the play when your screen shows just a fraction of the data. Imagine that you have some data source with lots of data items, but your collection view (or table view) just shows a dozen of items, so when you scroll (if your collectionView layout allows you to do this) some cells will become invisible, so they can be reused by CollectionView.

With respect to the date of the question I tend to think that this answer is kind of irrelevant to you, so I just leave it here for historical reasons.
